name: buy_tickets_design
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/efe-kurnaz.jpg
    - assets/rodion-kutsaev.jpeg
    - assets/steve-johnson.jpeg
  fonts:
    - family: SF Pro Display
      fonts:
      - asset: fonts/SF-Pro-Display-Ultralight.otf
        weight: 100
      - asset: fonts/SF-Pro-Display-Thin.otf
        weight: 200
      - asset: fonts/SF-Pro-Display-Light.otf
        weight: 300
      - asset: fonts/SF-Pro-Display-Regular.otf
        weight: 400
      - asset: fonts/SF-Pro-Display-Medium.otf
        weight: 500
      - asset: fonts/SF-Pro-Display-Semibold.otf
        weight: 600
      - asset: fonts/SF-Pro-Display-Bold.otf
        weight: 700
      - asset: fonts/SF-Pro-Display-Heavy.otf
        weight: 800
      - asset: fonts/SF-Pro-Display-Black.otf
        weight: 900